<ips:template parameters=""/>
{{if settings.hetrixapi_high_load_show AND $results = json_decode( \IPS\Settings::i()->hetrixapi_cpu_load_stats, TRUE ) And \count($results)}}

<div class="ipsBox ipsPad">
    <div class='ipsType_richText ipsType_normal'>Show Stats</div>
</div>








<table class="styled-table">
    <thead>
    <tr>
        <th>Name</th>
        <th>CPU Usage</th>
        <th>RAM Usage</th>
    </tr>
    </thead>
    <tbody>
    {{foreach $results as $i => $key}}
    <tr>
        <td> {$key['name']} </td>
        <td> {$key['cpu']}% </td>
        <td> {$key['ram']}% </td>
    </tr>
    {{endforeach}}
    </tbody>
</table>
{{endif}}


<style>
    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    .styled-table thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
    }
    .styled-table th,
    .styled-table td {
        padding: 12px 15px;
    }
    .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }

    .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }

    .styled-table tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
    }
    .styled-table tbody tr.active-row {
        font-weight: bold;
        color: #009879;
    }

</style>